INSERT INTO TEMP_STAFF_INSURANCE
(EMP_NO,INSURANCE_YYMM,HOUR_RATE,HOURS,SALARY,LABOR_INSURANCE,HEALTH_INSURANCE,RETIRE_INSURANCE,UPDATE_DATE,UPDATE_USER,EMP_NAME)
VALUES('T00001','202103',200,50,23000,23800,23800,23800, CURRENT_DATE,'admin','userTest');

INSERT INTO TEMP_STAFF_SALARY(
   SALARYYM                   ,
   EMP_NO                     ,
   UPDATE_DATE                ,
   UPDATE_USER                ,
   REMARK
   )
   VALUES('202103','T00001',CURRENT_DATE,'admin','testData');