 DROP TABLE IF EXISTS TEMP_TEMPSTAFF_SALARY;
 DROP TABLE IF EXISTS TEMP_TEMPSTAFF_INSURANCE;
 
 CREATE TABLE TEMP_TEMPSTAFF_SALARY
 (
   SALARYYM                   VARCHAR2(6 BYTE)   NOT NULL,
   UNIT_NAME                  VARCHAR2(30 BYTE),
   EMP_TYPE                   VARCHAR2(1 BYTE),
   EMP_NAME                   VARCHAR2(12 BYTE),
   EMP_NO                     VARCHAR2(6 BYTE)   NOT NULL,
   SALARY                     NUMBER,
   HOUR_RATE                  NUMBER,
   HOURS                      NUMBER,
   DAYS                       NUMBER,
   RETIRE_PAY                 NUMBER,
   FAMILY_MEM                 NUMBER,
   HEALTH_INSU_MEM            NUMBER,
   LABOR_INSU                 NUMBER,
   LABOR_INSU_MEM             NUMBER,
   OVER_65                    VARCHAR2(1 BYTE),
   LABOR_INSU_DIFF            NUMBER,
   LABOR_INSU_COM_DIFF        NUMBER,
   HEALTH_INSU                NUMBER,
   HEALTH_INSU_DIFF           NUMBER,
   HEALTH_INSU_COM_DIFF       NUMBER,
   RETIRE_INSU                NUMBER,
   RETIRE_INSU_DIFF           NUMBER,
   RETIRE_INSU_COM_DIFF       NUMBER,
   OTHER_IN                   NUMBER,
   OTHER_OUT                  NUMBER,
   ONBOARD_DATE               VARCHAR2(10 BYTE),
   RESIGNATION_DATE           VARCHAR2(10 BYTE),
   LABOR_APPLICATION          VARCHAR2(1 BYTE),
   HEALTH_APPLICATION         VARCHAR2(1 BYTE),
   WORK_OVERTIME1             NUMBER,
   WORK_OVERTIME2             NUMBER,
   WORK_OVERTIME3             NUMBER,
   WORK_OVERTIME4             NUMBER,
   WORK_OVERTIME5             NUMBER,
   CAL_SALARY                 NUMBER,
   CAL_LABOR_INSU_SELF        NUMBER,
   CAL_LABOR_INSU_COM         NUMBER,
   CAL_LABOR_INSU_COM_INJURY  NUMBER,
   CAL_RETIRE_INSU_SELF       NUMBER,
   CAL_RETIRE_INSU_COM        NUMBER,
   CAL_HEALTH_INSU_SELF       NUMBER,
   CAL_HEALTH_INSU_COM        NUMBER,
   CAL_REPAYMENT_FUND         NUMBER,
   CAL_WELFARE                NUMBER,
   UPDATE_DATE                DATE,
   UPDATE_USER                VARCHAR2(18 BYTE),
   REMARK                     VARCHAR2(60 BYTE)
 );

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.SALARYYM IS '薪資年月(西元)';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.UNIT_NAME IS '員工單位名稱';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.EMP_TYPE IS '員工類別(S:工讀生,M:按摩員,C:顧問)';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.EMP_NAME IS '員工姓名';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.EMP_NO IS '員工編號';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.SALARY IS '月薪';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HOUR_RATE IS '時薪';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HOURS IS '時數';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.DAYS IS '在職日數';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.RETIRE_PAY IS '勞退自提';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.FAMILY_MEM IS '眷屬加保';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HEALTH_INSU_MEM IS '健保計費人數';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.LABOR_INSU IS '勞保保額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.LABOR_INSU_MEM IS '勞保計費人數';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.OVER_65 IS '超過65歲';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.LABOR_INSU_DIFF IS '勞保個人差額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.LABOR_INSU_COM_DIFF IS '勞保公司差額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HEALTH_INSU IS '健保保額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HEALTH_INSU_DIFF IS '健保個人差額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HEALTH_INSU_COM_DIFF IS '健保公司差額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.RETIRE_INSU IS '勞退保額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.RETIRE_INSU_DIFF IS '勞退個人差額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.RETIRE_INSU_COM_DIFF IS '勞退公司差額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.OTHER_IN IS '其他應領';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.OTHER_OUT IS '其他應扣';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.ONBOARD_DATE IS '到職日';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.RESIGNATION_DATE IS '離職日';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.LABOR_APPLICATION IS '是否加保勞保';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.HEALTH_APPLICATION IS '是否加保健保';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.WORK_OVERTIME1 IS '第一類加班費1.3334';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.WORK_OVERTIME2 IS '第二類加班費1.6667';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.WORK_OVERTIME3 IS '第三類加班費2.6667';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.WORK_OVERTIME4 IS '第四類加班費2';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.WORK_OVERTIME5 IS '第五類加班費1';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_SALARY IS '計算後薪資';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_LABOR_INSU_SELF IS '勞保個人負擔';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_LABOR_INSU_COM IS '勞保公司負擔';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_LABOR_INSU_COM_INJURY IS '勞保公司負擔_職災';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_RETIRE_INSU_SELF IS '勞退個人負擔';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_RETIRE_INSU_COM IS '勞退公司負擔';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_HEALTH_INSU_SELF IS '健保個人負擔';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_HEALTH_INSU_COM IS '健保公司負擔';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_REPAYMENT_FUND IS '工資墊償';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.CAL_WELFARE IS '福利金';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.UPDATE_DATE IS '更新日期';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.UPDATE_USER IS '更新人員';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_SALARY.REMARK IS '備註';


 CREATE TABLE TEMP_TEMPSTAFF_INSURANCE
 (
   EMPNO             VARCHAR2(10 BYTE),
   INSURANCEYYMM     VARCHAR2(10 BYTE),
   HOUR_RATE         NUMBER,
   HOURS             NUMBER,
   SALARY            NUMBER,
   LABOR_INSURANCE   NUMBER,
   HEALTH_INSURANCE  NUMBER,
   RETIRE_INSURANCE  NUMBER,
   UPDATE_DATE       DATE,
   UPDATE_USER       VARCHAR2(18 BYTE),
   EMPNAME           VARCHAR2(15 BYTE)
 );

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.EMPNO IS '員工編號';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.INSURANCEYYMM IS '保額月份';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.HOUR_RATE IS '時薪';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.HOURS IS '時數';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.SALARY IS '月薪';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.LABOR_INSURANCE IS '勞保保額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.HEALTH_INSURANCE IS '健保保額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.RETIRE_INSURANCE IS '勞退保額';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.UPDATE_DATE IS '更新日期';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.UPDATE_USER IS '更新人員';

 COMMENT ON COLUMN TEMP_TEMPSTAFF_INSURANCE.EMPNAME IS '員工姓名';

